# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbf585271a6fe10c8aaa86286f7008500e71a97280399cd363190e2eec5ec36479b1a4ec3e9776ba9c7c6c60d4a9c4dd02a66f143f3ec0da46cf502906805fd

test:
  secret_key_base: 34987bf0a08e2cde1c6c3b2ef1f52712fe124118cd11c22cc43c750654527d2bd7e13b2f35191aa0d2aa39a44aaaa450fa76a06dd1d31f7e4758c5c9e3a2a1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
